name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()  # deploy only if tests passed

    steps:
    - uses: actions/checkout@v4

    - name: Deploy
      run: |
        echo "Deploying application..."
        # Your deployment commands here
